### ISSUE TITLE
[Feature] Validate the URL property

### ISSUE THREAD

**Issue by HebaruSan** [DasSkelett/AVC-VersionFileValidator#2]
## Motivation

The "URL" property is extremely useful when used correctly, and useless otherwise. If it's set to the URL of a remote copy of the version file, then authors can:

- notify users of new versions
- update the current compatibility of already released mods without changing the downloads

## Suggestion

Parse the URL property and check that:

- It's a URL
- It's not a 404
- It's a JSON file
- It's a version file

If any of these fail, raise a warning or error (again, I'm not sure whether there's a distinction).

**Comment by DasSkelett** [comment]
Thanks for the suggestion, good idea!

As mentioned in #1, the PR can only be set to failed or success AFAIK.
However I think this one would be fine raising an error and setting the PR status to failed, because the spec explicitly says `Location of a remote version file for update checking`. So if it's there, it should be valid.

Will take a look.
